using Energy8.Identity.Shared.Core.Contracts.Dto.Common;

namespace Energy8.Identity.Shared.Core.Contracts.Dto.Auth
{
    /// <summary>
    /// Data transfer object for Telegram user authentication data.
    /// </summary>
    /// <remarks>
    /// Contains verified user information and authentication data from Telegram login widget.
    /// Implements Telegram's secure authentication protocol using data hashing.
    /// Used for both new user registration and existing user authentication.
    /// </remarks>
    [System.Serializable]
    public class TelegramUserDto : DtoBase
    {
        /// <summary>
        /// Telegram authentication data hash
        /// </summary>
        /// <remarks>
        /// - HMAC-SHA-256 signature of data fields
        /// - Used to verify data authenticity
        /// - Generated by Telegram using bot token
        /// </remarks>
        public string Hash { get; set; }

        /// <summary>
        /// Telegram user's unique identifier
        /// </summary>
        /// <remarks>
        /// Permanent user ID in Telegram system
        /// </remarks>
        public long Id { get; set; }

        /// <summary>
        /// User's first name from Telegram profile
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// User's last name from Telegram profile
        /// </summary>
        /// <remarks>
        /// Optional. May be null if not set in Telegram
        /// </remarks>
        public string LastName { get; set; }

        /// <summary>
        /// User's username from Telegram
        /// </summary>
        /// <remarks>
        /// Optional. May be null if user hasn't set a username
        /// </remarks>
        public string Username { get; set; }

        /// <summary>
        /// URL to user's Telegram profile photo
        /// </summary>
        public string PhotoUrl { get; set; }

        /// <summary>
        /// Authentication timestamp
        /// </summary>
        /// <remarks>
        /// Unix timestamp when authentication occurred
        /// </remarks>
        public long AuthDate { get; set; }

        /// <summary>
        /// User's language code
        /// </summary>
        /// <remarks>
        /// Optional. IETF language tag
        /// </remarks>
        public string LanguageCode { get; set; }

        /// <summary>
        /// Whether user allows writing private messages
        /// </summary>
        public bool AllowsWriteToPm { get; set; }

        /// <summary>
        /// Query identifier
        /// </summary>
        /// <remarks>
        /// Optional. Used in some Telegram authentication flows
        /// </remarks>
        public string QueryId { get; set; }

        /// <summary>
        /// Default constructor for Unity serialization
        /// </summary>
        public TelegramUserDto()
        {
            FirstName = "Player";
        }

        /// <summary>
        /// Constructor with required parameters
        /// </summary>
        public TelegramUserDto(string hash, long id, string firstName, string photoUrl, long authDate)
        {
            Hash = hash;
            Id = id;
            FirstName = firstName ?? "Player";
            PhotoUrl = photoUrl;
            AuthDate = authDate;
        }
    }

    /// <summary>
    /// DTO for linking Telegram account to existing user.
    /// </summary>
    /// <remarks>
    /// Used when adding Telegram authentication to an existing account.
    /// Requires valid authentication ID from the current session.
    /// </remarks>
    [System.Serializable]
    public class TelegramLinkDto : DtoBase
    {
        /// <summary>
        /// Telegram user data for linking
        /// </summary>
        public TelegramUserDto TelegramData { get; set; }

        /// <summary>
        /// Authentication ID for linking with existing account
        /// </summary>
        public string AuthId { get; set; }

        /// <summary>
        /// Default constructor for Unity serialization
        /// </summary>
        public TelegramLinkDto()
        {
        }

        /// <summary>
        /// Constructor with parameters
        /// </summary>
        public TelegramLinkDto(TelegramUserDto telegramData, string authId)
        {
            TelegramData = telegramData;
            AuthId = authId;
        }
    }
}